version: 1.1.0

# Avatar url
avatar: /img/avatar.jpg
favicon: /img/avatar.jpg

# If the blog is not placed in the root directory, you can configure this path to resolve static file path errors.
# Ex: if the access URL is exemple.com/blog, you need to set blog_path: /blog
blog_path: /

# Social
link:
  theme: color  # Link style, color: colored icons, white: black and white icons
  items:
    rss: /atom.xml
    github: https://github.com/wem-r
    facebook:
    twitter:
    linkedin:
    instagram:
    reddit:

########## Multi-Author Mode ############
author:
  on: false
  authors:
    author1: wem
    author2: not-wem
##############################

# Article Category Settings
category:
  num: true # Display the number of articles in each category
  sub: true # Enable multi-level categories
  sort:
    - Reading
    - Tools
    - Frontend
    - Backend
    - Database
    - DevOps
  width:
    lg: 120 # Left category width for screens larger than 1468px
    md: 100 # Left category width for screens between 1024px and 1468px
    sm: 100 # Left category width for screens between 426px and 1024px (e.g., iPad)

# Multi-level category explanation:
# For example, if multiple menus are set in an article, it defaults to a multi-level menu, such as: Tools > Hexo
# categories:
#  - Tools
#  - Hexo

# Shortcut Keys
shortcutKey: true

#  Custom Menu at the Bottom Left
menu:
  about:  # 'About' button
    on: true # Whether to display
    url: /about  # Redirect link
    type: 1 # Redirect type: 1: Async redirect within the site, 2: Redirect to the current page, 3: Open in a new tab
  friend: # 'Friend Links' button
    on: true # Whether to display
  menus: # Additional menus under 'menus', like these three dynamic menus: Menu 1, Menu 2, Menu 3
    photo_album:
      on: false
      url: /photo
      type: 1  # Redirect type 1: Async redirect within the site
    yelog:
      on: false
      url: http://ais.wemy.ninja
      type: 2  # Redirect type 2: Redirect to the current page
    github:
      on: false
      url: https://github.com/wem-r
      type: 3  # Redirect type 3: Open in a new tab

# aticle Disclaimer
article_txt: Please credit the source when reposting. Feel free to verify the references in the article, and point out any errors or unclear expressions. You can comment in the section below or email jaytp@qq.com.

# copyright 
bottom_text: ©2016-2020 Yelog
#  If left blank, it defaults to ©2017 author (where 'author' is configured in the Hexo root _config.yml file).

# donation feature
reward: false

searchAll: false
# true enables full-text search
# To enable this feature, follow these steps:
# 1. Run npm install hexo-generator-search --save in the Hexo root directory to install the plugin.
# 2. Add the following configuration to _config.yml in the Hexo root directory:

copyright: false

word_count: false
# To enable this feature, install the plugin: Run npm i hexo-wordcount --save in the Hexo root directory.

# Busuanzi Website Counter Settings : http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  on: truefalse
  site_visit: false
  page_visit: false

########## Custom Style Settings ##############

# Table of Contents | Article TOC
toc:
  max_depth: 3  # Maximum heading levels in the TOC (1 - 6 for h1 - h6)

# Article List - Hover Style  
# If left empty, the default effect will be applied.
article_list:
  title: '#383636'  # Article list title color
  datetime: '#5e5e5f'  # Article publication date color
  hover:
    background: '#e2e0e0'  # Background color; examples: '#c1bfc1', '#fbf4a8'
    color:     # Text color; examples: '#ffffff'
# Note: If the color contains '#', enclose it in single quotes ' '.


# Article List Background Image
article_bg_img:
  on: false  # Whether to enable
  src: https://i.loli.net/2019/07/22/5d3521411f3f169375.png  # Background image URL
  opacity: 0.3  # Background image opacity, range 0 to 1


# List Style
list: normal  
# normal: Standard style  
# thread: List with a border around it  

# Blockquote Style
blockquote: github  
# github: Similar to GitHub's blockquote style  
# bracket: Similar to the style with large brackets on both sides  

# Table Style
table: green_title  
# If empty, it will resemble GitHub's table style  
# green: Green style  
# green_title: Table with cyan-colored headers  

# Homepage Background Image
index_bg_img:  

# Other Page Background Image
other_bg_img:  

# Image Click-to-Resize Style
img_resize: default  
# Available values:  
# default: Default (simple enlargement script)  
# photoSwipe: Use the photoSwipe plugin


# Code Block Highlight Style, Markdown Syntax `demo`
code:
  theme: dark-red  # Supported themes:  
  # dark-red: Red text (default)  
  # github: GitHub style (gray background, black text)

highlight:
  on: true  # true enables code highlighting, but requires disabling highlight in the blog's _config.yml  
  lineNum: false  # true shows line numbers  
  copy: true  # Copy function enabled  
  theme: atom-light  # Code highlight theme, you can preview it at https://highlightjs.org/static/demo/  
  # Supported themes:  
  # sublime: Sublime-style highlight  
  # darcula: Dark theme from IDEA  
  # atom-dark: Atom's dark theme  
  # atom-light: Atom's light theme  
  # github: GitHub-style highlight  
  # github-gist: GitHub Gist theme  
  # brown-paper: Brown paper effect  
  # gruvbox-light: Gruvbox light theme  
  # gruvbox-dark: Gruvbox dark theme  
  # rainbow:  
  # railscasts:  
  # sunburst:  
  # kimbie-dark:  
  # kimbie-light:  
  # school-book: Paper effect  
  # zenbum: OSChina uses this highlight theme


# MathJax Math Formula Support
mathjax:
  on: true  # Whether to enable MathJax
  per_page: false  # If rendering only a single page, set this to false, and include mathjax: true in the page

# Mermaid Support
mermaid:
  on: false  # Whether to enable Mermaid
  cdn: //cdn.jsdelivr.net/npm/mermaid@8.4.2/dist/mermaid.min.js  # CDN link for Mermaid
  # cdn: //cdnjs.cloudflare.com/ajax/libs/mermaid/8.3.1/mermaid.min.js  # Alternative CDN
  options:  # More configuration details can be found at https://mermaidjs.github.io/#/mermaidAPI
    theme: 'default'  # Theme for Mermaid diagrams
    startOnLoad: true  # Start rendering when the page loads
    flowchart:
      useMaxWidth: false  # Whether to use the maximum width for flowchart
      htmlLabels: true  # Whether to use HTML labels in flowchart


##############################

# 友情链接
friends:
  叶落阁: http://yelog.org/

########## Comment Settings #############
comment:
  on: false  # Whether to enable comments
  type: gitalk  # Comment system: gitalk, disqus, gitment, utteranc, livere, giscus. Note: configure the corresponding system below.
  comment_count: true  # Show comment count below the article title. Currently supports only gitalk and disqus.
  ## Usage instructions: https://yelog.org//2020/05/23/3-hexo-comment/
# Configuration for each comment system ↓↓

disqus:
  shortname:  # Disqus comment system, GFW-certified in September 2016, not accessible in mainland China.
  # Get shortname: https://help.disqus.com/customer/en/portal/articles/466208-what-s-a-shortname-

gitalk:
  githubID: yelog  # GitHub username
  repo: yelog.github.io  # Repository to use for GitHub issues
  ClientID:  # GitHub OAuth application Client ID
  ClientSecret:  # GitHub OAuth application Client Secret
  adminUser: yelog  # Admin user, must be a collaborator with write access to the above repository
  distractionFreeMode: true  # Full-screen distraction-free mode
  language: zh-CN  # Language: Supported options are en, zh-CN, zh-TW
  perPage: 10  # Number of comments per page (default is 10, maximum is 100)
# gitalk: A third-party chat plugin built using GitHub Issues
# https://github.com/gitalk/gitalk
# Parameter description:
# githubID: GitHub username
# repo: Repository to use for GitHub Issues
# ClientID and ClientSecret are obtained by creating an OAuth application: https://github.com/settings/applications/new
# adminUser: Must be a collaborator with write access to the repository (use your GitHub username)
# distractionFreeMode: Fullscreen mode for distraction-free reading
# language: Supported languages: en, zh-CN, zh-TW
# perPage: Number of comments per page (default is 10, maximum is 100)



gitment:
  owner: yelog  # GitHub repository owner
  repo: yelog.github.io  # Repository for GitHub issues
  client_id:  # GitHub OAuth application Client ID
  client_secret:  # GitHub OAuth application Client Secret
  # gitment: A comment system built using GitHub Issues
  # Open-source repository: https://github.com/imsun/gitment
  # Usage instructions: 

livere:
  data_uid:  # Livere comment system user ID
  # Livere: http://livere.com/
  # Usage instructions: https://yelog.org//2020/05/23/3-hexo-comment/

utteranc:
  repo: xxx/xxx.github.io  # Repository for hosting comments, use your own newly created repository
  issue_term: pathname  # Mapping between Issue and blog articles
  label: utteranc  # Label for the created Issue
  theme: github-light  # Theme, check official documentation for other options: https://utteranc.es/#heading-theme
# Official documentation: https://utteranc.es/
# Usage instructions: https://yelog.org//2020/05/23/3-hexo-comment/

giscus:
  repo: xxx/xxx  # Repository used to host comments
  repoId: xxx  # Repository ID, obtained from the Giscus website
  category: General  # Discussion category
  categoryId: x  # Category ID, obtained from the Giscus website
  mapping: pathname  # Mapping between GitHub discussion and blog articles, options: pathname, url, title, og:title
  strict: 0  # Whether to use strict title matching, options: 0 (no), 1 (yes)
  reactionsEnabled: 1  # Whether to enable GitHub discussion Reactions, options: 0 (no), 1 (yes)
  emitMetadata: 1  # Whether to output GitHub discussion metadata, options: 0 (no), 1 (yes)
  inputPosition: top  # Position of the input box, options: top, bottom
  theme: light  # Theme, check the Giscus website for supported themes
  lang: zh-CN  # Theme language, check the Giscus website for supported languages
  loading: lazy  # Whether to enable lazy loading
  # Official documentation: https://giscus.app/


##############################

########## CDN Settings #############
CDN:
  jquery: //cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  jquery_cookie: //cdn.jsdelivr.net/npm/jquery.cookie@1.4.1/jquery.cookie.min.js
  highlight: //cdn.jsdelivr.net/npm/highlightjs@9.16.2/highlight.pack.min.js
  pjax: //cdn.jsdelivr.net/npm/jquery-pjax@2.0.1/jquery.pjax.min.js
  animate: //cdn.jsdelivr.net/npm/animate.css@4.1.0/animate.min.css
  nprogres_js: //cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.min.js
  mathjax: //cdn.jsdelivr.net/npm/mathjax@2.7.8/unpacked/MathJax.js?config=TeX-MML-AM_CHTML
  photoswipe_js: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.min.js
  photoswipe_ui_js: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe-ui-default.min.js
  photoswipe_css: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/photoswipe.min.css
  photoswipe_skin_css: //cdn.jsdelivr.net/npm/photoswipe@4.1.3/dist/default-skin/default-skin.min.css
##############################
